name: Adnan Shaikh
author: Adnan Shaikh
title: "Adnan Shaikh's Blog"
description: "Adnan Shaikh's personal website and blog."
keywords: blog programming student resume technology talks
tagline: A blog to enhance my delusion of professionalism
logo: /images/me.jpg

url: adnanshaikh.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-redirect-from

sass:
    sass_dir: assets
    style: compressed

paginate: 6	
paginate_path: "blog/page:num"

markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  input: GFM
  math_engine: mathjax
  hard_wrap: false

exclude:
  - Rakefile
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - first_setup.md
  
#disqus: adnanshaikh
analytics: UA-88085331-1
